"use client";

import type { Metadata } from "next";
import React from "react";

import { Inter } from "next/font/google";
import Link from "next/link";
import StoreProvider from "./StoreProvider";
import Header from "../components/Header";
import Navigation from "../components/Navigation";
import "./globals.css";
import { useAppDispatch } from "../redux/hooks";
import { toogleTheme } from "../redux/features/themesSlice";
import store from "../redux/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          {" "}
          <Header />
          <div className="">
            <Navigation />
          </div>
          <nav></nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
