import type { Metadata } from "next";
import React from "react";

import { Inter } from "next/font/google";
import Link from "next/link";
import StoreProvider from "./StoreProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/portfolio">Portfolio</Link>
          </nav>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
